"""Native meshing admission and quality contracts."""

from .domains import (
    BoundaryLayerIntent,
    BoxSelector,
    DomainKind,
    InterfaceKind,
    InterfaceSpec,
    MaterialRegionSpec,
    MeshSpec,
    PatchKind,
    PatchSpec,
    RefinementSpec,
    ZoneMotion,
    ZoneSpec,
)
from .export import (
    SolverMeshExport,
    build_solver_exports,
    solver_mapping_digest,
    write_solver_mapping,
)
from .gmsh_adapter import MeshPlan, MeshReceipt, plan_gmsh_mesh
from .morph import (
    MeshUpdateAction,
    MeshUpdateReceipt,
    MorphReceipt,
    UpdatePolicy,
    decide_update_strategy,
    morph_affine,
    select_mesh_update,
)
from .native_mesh import (
    GmshCapability,
    InterfaceGroup,
    NativeMeshReceipt,
    PeriodicPair,
    build_native_mesh,
    duct_mesh_spec,
    mesh_spec_digest,
    probe_gmsh,
)
from .quality import MeshQuality, compute_quality, evaluate_quality_gate
from .semantics import (
    ExportNeed,
    InterfaceDeclaration,
    MaterialDeclaration,
    MeshRequestMapping,
    PatchDeclaration,
    ResolvedMeshRequest,
    SemanticEntity,
    SemanticMeshRequest,
    SemanticTopologyReceipt,
    ZoneDeclaration,
    resolve_semantic_mesh_request,
    semantic_request_from_topology,
    semantic_topology_from_model,
)

__all__ = [
    "MeshPlan",
    "MeshReceipt",
    "plan_gmsh_mesh",
    "BoundaryLayerIntent",
    "BoxSelector",
    "DomainKind",
    "InterfaceKind",
    "InterfaceSpec",
    "MaterialRegionSpec",
    "MeshSpec",
    "PatchKind",
    "PatchSpec",
    "RefinementSpec",
    "ZoneMotion",
    "ZoneSpec",
    "SolverMeshExport",
    "build_solver_exports",
    "solver_mapping_digest",
    "write_solver_mapping",
    "MeshUpdateAction",
    "MeshUpdateReceipt",
    "MorphReceipt",
    "UpdatePolicy",
    "decide_update_strategy",
    "morph_affine",
    "select_mesh_update",
    "GmshCapability",
    "InterfaceGroup",
    "NativeMeshReceipt",
    "PeriodicPair",
    "build_native_mesh",
    "duct_mesh_spec",
    "mesh_spec_digest",
    "probe_gmsh",
    "MeshQuality",
    "compute_quality",
    "evaluate_quality_gate",
    "ExportNeed",
    "InterfaceDeclaration",
    "MaterialDeclaration",
    "MeshRequestMapping",
    "PatchDeclaration",
    "ResolvedMeshRequest",
    "SemanticEntity",
    "SemanticMeshRequest",
    "SemanticTopologyReceipt",
    "ZoneDeclaration",
    "resolve_semantic_mesh_request",
    "semantic_request_from_topology",
    "semantic_topology_from_model",
]
