"""VEHICLE-SYSTEMS 07: vehicle aeroacoustics and community-noise optimization.

Rotor/propulsor tonal and broadband screening from declared blade loading and
order data, airframe contributor seams (trailing-edge, high-lift,
landing-gear), rotor-airframe interaction screening, transient-data ingestion
for higher-fidelity propagation, Doppler/vehicle-motion handling, observer
metrics (OASPL/SEL/simplified EPNL with cited standards and preserved raw
spectra), community-noise footprints over observer grids and trajectories, and
a noise objective/constraint feed for the generic campaign. Native CAA/FW-H
propagation is capability-gated and fails closed; every result carries
source/fidelity/units/validity/input-hash/software-identity/provenance.

Public API (other workstreams import these exact paths):

    from aeroworkbench_vehicle_systems.aeroacoustics import (
        RotorSpec, blade_passing_frequency_hz, shaft_frequency_hz,
        rotor_tonal_orders, screen_rotor_tones,
        screen_broadband, AirframeContributor, AirframeReference,
        screen_airframe_source, screen_rotor_airframe_interaction,
        ObserverSpec, EnvironmentSpec, FlightState, Weighting,
        doppler_factor, distance_m, a_weighting_db, c_weighting_db,
        PropagatableLine, lines_from_rotor, lines_from_broadband,
        lines_from_airframe, lines_from_interaction,
        propagate_to_observer, ingest_surface_record,
        propagate_spectrum_to_observer,
        assess_observer_noise, overall_level_db, sound_exposure_level_db,
        effective_perceived_noise_level_db,
        FootprintGrid, sample_footprint, footprint_from_trajectory,
        NoiseTradeModel, noise_objective, noise_constraint,
        noise_trade_evaluator, noise_campaign_outputs,
        native_caa_status, require_native_caa, propagate_fw_h_native,
    )
"""

from .contracts import (
    NOISE_UNITS,
    SOFTWARE_NAME,
    SOFTWARE_VERSION,
    NoiseFidelity,
    NoiseMeta,
    NoiseValidity,
)
from .errors import (
    AeroacousticError,
    CapabilityUnavailable,
    ContractError,
    ValidityError,
)
from .footprints import (
    FootprintCell,
    FootprintGrid,
    FootprintResult,
    TrajectoryFootprint,
    TrajectorySample,
    footprint_from_trajectory,
    sample_footprint,
)
from .metrics import (
    EPNL_MODEL,
    NoiseMetrics,
    assess_observer_noise,
    effective_perceived_noise_level_db,
    overall_level_db,
    sound_exposure_level_db,
)
from .native import (
    NATIVE_REQUIREMENT,
    CapabilityState,
    NativeCAABackend,
    native_caa_status,
    propagate_fw_h_native,
    require_native_caa,
)
from .observers import (
    WEIGHTING_STANDARDS,
    EnvironmentSpec,
    FlightState,
    ObserverSpec,
    Weighting,
    a_weighting_db,
    absorption_loss_db,
    apply_weighting,
    c_weighting_db,
    closing_speed_m_s,
    distance_m,
    doppler_factor,
    spherical_transmission_loss_db,
)
from .optimization import (
    NOISE_OUTPUT,
    THRUST_OUTPUT,
    NoiseTradeModel,
    noise_campaign_outputs,
    noise_constraint,
    noise_objective,
    noise_trade_evaluator,
)
from .propagation import (
    ObserverNoiseLine,
    ObserverNoiseResult,
    PropagatableLine,
    ingest_surface_record,
    lines_from_airframe,
    lines_from_broadband,
    lines_from_interaction,
    lines_from_rotor,
    propagate_spectrum_to_observer,
    propagate_to_observer,
)
from .sources import (
    AirframeContributor,
    AirframeReference,
    AirframeScreening,
    BroadbandLine,
    BroadbandScreening,
    InteractionLine,
    InteractionScreening,
    RotorScreening,
    RotorSpec,
    RotorTone,
    RotorToneLine,
    blade_passing_frequency_hz,
    rotor_tonal_orders,
    screen_airframe_source,
    screen_broadband,
    screen_rotor_airframe_interaction,
    screen_rotor_tones,
    shaft_frequency_hz,
)

__all__ = [
    "EPNL_MODEL",
    "NATIVE_REQUIREMENT",
    "NOISE_OUTPUT",
    "NOISE_UNITS",
    "SOFTWARE_NAME",
    "SOFTWARE_VERSION",
    "THRUST_OUTPUT",
    "WEIGHTING_STANDARDS",
    "AeroacousticError",
    "AirframeContributor",
    "AirframeReference",
    "AirframeScreening",
    "BroadbandLine",
    "BroadbandScreening",
    "CapabilityState",
    "CapabilityUnavailable",
    "ContractError",
    "EnvironmentSpec",
    "FlightState",
    "FootprintCell",
    "FootprintGrid",
    "FootprintResult",
    "InteractionLine",
    "InteractionScreening",
    "NativeCAABackend",
    "NoiseFidelity",
    "NoiseMeta",
    "NoiseMetrics",
    "NoiseTradeModel",
    "NoiseValidity",
    "ObserverNoiseLine",
    "ObserverNoiseResult",
    "ObserverSpec",
    "PropagatableLine",
    "RotorScreening",
    "RotorSpec",
    "RotorTone",
    "RotorToneLine",
    "TrajectoryFootprint",
    "TrajectorySample",
    "ValidityError",
    "Weighting",
    "a_weighting_db",
    "absorption_loss_db",
    "apply_weighting",
    "assess_observer_noise",
    "blade_passing_frequency_hz",
    "c_weighting_db",
    "closing_speed_m_s",
    "distance_m",
    "doppler_factor",
    "effective_perceived_noise_level_db",
    "footprint_from_trajectory",
    "ingest_surface_record",
    "lines_from_airframe",
    "lines_from_broadband",
    "lines_from_interaction",
    "lines_from_rotor",
    "noise_campaign_outputs",
    "noise_constraint",
    "native_caa_status",
    "noise_objective",
    "noise_trade_evaluator",
    "overall_level_db",
    "propagate_fw_h_native",
    "propagate_spectrum_to_observer",
    "propagate_to_observer",
    "require_native_caa",
    "rotor_tonal_orders",
    "sample_footprint",
    "screen_airframe_source",
    "screen_broadband",
    "screen_rotor_airframe_interaction",
    "screen_rotor_tones",
    "shaft_frequency_hz",
    "sound_exposure_level_db",
    "spherical_transmission_loss_db",
]
