"""Generic transition, turbulence, roughness, and aerodynamic-model validity.

One product-neutral capability for every viscous aerodynamic flow: fixed-wing
external flows, open propulsors, internal passages, and rotating blade passages.
It represents laminar/transitional/turbulent regimes, an explicit
provenance-backed model/fidelity ladder, near-wall treatment as a mesh-checked
requirement, explicit surface roughness, transition/separation/model-disagreement
diagnostics, solver-adapter derivation, and portable benchmarks.

Public API (downstream issues import these exact paths):

    from aeroworkbench_turbulence import (
        FlowState, FlowRegime, TransitionState, RegimeThresholds,
        ReferenceScales, RegimeClassification, classify_regime,
        flow_state_from_fluid, reynolds_number, mach_number,
        EXTERNAL_FLOW_THRESHOLDS, INTERNAL_FLOW_THRESHOLDS,
        LOW_REYNOLDS_THRESHOLDS,
        RoughnessSpec, RoughnessModel, make_roughness,
        roughness_from_degradation, apply_roughness_increment,
        TurbulenceModel, ModelValidity, ModelSelection, TurbulencePolicy,
        MODEL_CATALOG, select_turbulence_model,
        select_turbulence_model_for_fidelity, plan_fidelity_escalation,
        WallTreatmentMode, WallTreatmentRequirement, MeasuredWallResolution,
        WallCompatibility, evaluate_wall_treatment, require_wall_treatment,
        wall_requirement_for_mode, wall_requirement_from_boundary_layer,
        first_cell_height_for_y_plus, inflation_total_thickness,
        DiagnosticsReport, ModelDisagreement, assess_diagnostics,
        compare_model_predictions, transition_location_fraction,
        skin_friction_distribution_flat_plate,
        SolverFlowModel, derive_solver_flow_model,
        openfoam_turbulence_properties, openfoam_wall_roughness,
        NativeTurbulenceBackend, NativeTurbulenceRequest,
        NativeTurbulenceResult, evaluate_native_turbulence,
        solve_native_turbulence_or_fail,
        BenchmarkCase, BenchmarkKind, BenchmarkResult,
        portable_benchmarks, run_benchmark,
    )

Every result carries source/fidelity/units/validity/input-hash/software-identity/
provenance. Native paths are capability-gated and fail closed; a screening
correlation is never relabelled native.
"""

from __future__ import annotations

from .adapter import (
    DEFAULT_ROUGHNESS_CONSTANT_CS,
    DEFAULT_ROUGHNESS_CONSTANT_SOURCE,
    ROUGHNESS_WALL_FUNCTION,
    NativeTurbulenceBackend,
    NativeTurbulenceCapability,
    NativeTurbulenceRequest,
    NativeTurbulenceResult,
    NativeTurbulenceSolution,
    SolverFlowModel,
    build_native_turbulence_request,
    derive_solver_flow_model,
    evaluate_native_turbulence,
    openfoam_turbulence_properties,
    openfoam_wall_roughness,
    probe_any_native_turbulence_capability,
    probe_native_turbulence_capability,
    require_native_turbulence_capability,
    solve_native_turbulence_or_fail,
)
from .benchmarks import (
    REGIME_INDEX,
    BenchmarkCase,
    BenchmarkKind,
    BenchmarkResult,
    portable_benchmarks,
    run_benchmark,
)
from .contracts import (
    SOFTWARE_IDENTITY,
    SOFTWARE_NAME,
    SOFTWARE_VERSION,
    TurbulenceFidelity,
    Validity,
    analytical_provenance,
    native_provenance,
)
from .diagnostics import (
    DiagnosticsReport,
    ModelDisagreement,
    assess_diagnostics,
    compare_model_predictions,
    intensity_sensitivity,
    pressure_coefficient,
    roughness_sensitivity,
    skin_friction_distribution_flat_plate,
    transition_location_fraction,
)
from .errors import (
    TurbulenceCapabilityUnavailableError,
    TurbulenceError,
    TurbulenceValidationError,
    TurbulenceValidityError,
)
from .models import (
    DEFAULT_TURBULENCE_POLICY,
    FIDELITY_RANK,
    MODEL_CATALOG,
    ModelSelection,
    ModelValidity,
    TurbulenceModel,
    TurbulencePolicy,
    fidelity_implementations,
    model_validity,
    plan_fidelity_escalation,
    select_turbulence_model,
    select_turbulence_model_for_fidelity,
)
from .regimes import (
    EXTERNAL_FLOW_THRESHOLDS,
    INTERNAL_FLOW_THRESHOLDS,
    LOW_REYNOLDS_THRESHOLDS,
    REGIME_THRESHOLD_PRESETS,
    CompressibilityRegime,
    FlowRegime,
    FlowState,
    ReferenceScales,
    RegimeClassification,
    RegimeThresholds,
    TransitionState,
    classify_regime,
    flow_state_from_fluid,
    mach_number,
    reynolds_number,
)
from .roughness import (
    SMOOTH_ROUGHNESS,
    RoughnessModel,
    RoughnessSpec,
    apply_roughness_increment,
    make_roughness,
    roughness_from_degradation,
)
from .wall import (
    BLASIUS_LAMINAR_SKIN_FRICTION,
    SCHLICHTING_TURBULENT_SKIN_FRICTION,
    WALL_TREATMENT_SOURCES,
    CorrelationRef,
    MeasuredWallResolution,
    WallCompatibility,
    WallTreatmentMode,
    WallTreatmentRequirement,
    evaluate_wall_treatment,
    first_cell_height_for_y_plus,
    first_cell_height_from_flow,
    inflation_total_thickness,
    laminar_skin_friction,
    require_wall_treatment,
    roughness_wall_effect,
    skin_friction_coefficient_flat_plate,
    turbulent_skin_friction,
    wall_requirement_for_mode,
    wall_requirement_from_boundary_layer,
)

__all__ = [
    "BLASIUS_LAMINAR_SKIN_FRICTION",
    "DEFAULT_ROUGHNESS_CONSTANT_CS",
    "DEFAULT_ROUGHNESS_CONSTANT_SOURCE",
    "DEFAULT_TURBULENCE_POLICY",
    "EXTERNAL_FLOW_THRESHOLDS",
    "FIDELITY_RANK",
    "INTERNAL_FLOW_THRESHOLDS",
    "LOW_REYNOLDS_THRESHOLDS",
    "MODEL_CATALOG",
    "REGIME_INDEX",
    "REGIME_THRESHOLD_PRESETS",
    "ROUGHNESS_WALL_FUNCTION",
    "SCHLICHTING_TURBULENT_SKIN_FRICTION",
    "SMOOTH_ROUGHNESS",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_NAME",
    "SOFTWARE_VERSION",
    "WALL_TREATMENT_SOURCES",
    "BenchmarkCase",
    "BenchmarkKind",
    "BenchmarkResult",
    "CompressibilityRegime",
    "CorrelationRef",
    "DiagnosticsReport",
    "FlowRegime",
    "FlowState",
    "MeasuredWallResolution",
    "ModelDisagreement",
    "ModelSelection",
    "ModelValidity",
    "NativeTurbulenceBackend",
    "NativeTurbulenceCapability",
    "NativeTurbulenceRequest",
    "NativeTurbulenceResult",
    "NativeTurbulenceSolution",
    "ReferenceScales",
    "RegimeClassification",
    "RegimeThresholds",
    "RoughnessModel",
    "RoughnessSpec",
    "SolverFlowModel",
    "TransitionState",
    "TurbulenceCapabilityUnavailableError",
    "TurbulenceError",
    "TurbulenceFidelity",
    "TurbulenceModel",
    "TurbulencePolicy",
    "TurbulenceValidationError",
    "TurbulenceValidityError",
    "Validity",
    "WallCompatibility",
    "WallTreatmentMode",
    "WallTreatmentRequirement",
    "analytical_provenance",
    "apply_roughness_increment",
    "assess_diagnostics",
    "build_native_turbulence_request",
    "classify_regime",
    "compare_model_predictions",
    "derive_solver_flow_model",
    "evaluate_native_turbulence",
    "evaluate_wall_treatment",
    "fidelity_implementations",
    "first_cell_height_for_y_plus",
    "first_cell_height_from_flow",
    "flow_state_from_fluid",
    "inflation_total_thickness",
    "intensity_sensitivity",
    "laminar_skin_friction",
    "mach_number",
    "make_roughness",
    "model_validity",
    "native_provenance",
    "openfoam_turbulence_properties",
    "openfoam_wall_roughness",
    "plan_fidelity_escalation",
    "portable_benchmarks",
    "pressure_coefficient",
    "probe_any_native_turbulence_capability",
    "probe_native_turbulence_capability",
    "require_native_turbulence_capability",
    "require_wall_treatment",
    "reynolds_number",
    "roughness_from_degradation",
    "roughness_sensitivity",
    "roughness_wall_effect",
    "run_benchmark",
    "select_turbulence_model",
    "select_turbulence_model_for_fidelity",
    "skin_friction_coefficient_flat_plate",
    "skin_friction_distribution_flat_plate",
    "solve_native_turbulence_or_fail",
    "transition_location_fraction",
    "turbulent_skin_friction",
    "wall_requirement_for_mode",
    "wall_requirement_from_boundary_layer",
]
