"""Canonical flying-vehicle state, reference frames, and unit-safe flight quantities.

Public API (later AIRFRAME/VEHICLE-SYSTEMS issues import these exact paths):

    from aeroworkbench_airframe import (
        FlyingVehicleState,
        vehicle_state_from_payload,
        canonical_vehicle_state,
        vehicle_state_hash,
        vehicle_state_provenance,
        vehicle_state_change_sections,
        airframe_invalidated_families,
        vehicle_design_parameters,
    )
"""

from .architecture import (
    MASS_SECTION,
    MOTION_SECTION,
    OPERATING_SECTION,
    REFERENCE_SECTION,
    SCHEMA_VERSION,
    FlyingVehicleState,
    airframe_invalidated_families,
    canonical_vehicle_state,
    vehicle_design_parameters,
    vehicle_state_change_sections,
    vehicle_state_from_payload,
    vehicle_state_hash,
    vehicle_state_provenance,
)
from .canonical import canonical_json, canonical_number, content_digest, normalize_numbers
from .derived import (
    DerivedQuantity,
    dynamic_pressure,
    equivalent_airspeed,
    mach_number,
    weight_force,
)
from .frames import (
    FRAME_CONVENTIONS,
    FRAME_KINDS,
    FRAME_PARENT_KIND,
    IDENTITY,
    Frame,
    frame_index,
    frame_rotation,
    matmul,
    matvec,
    rotate_vector,
    rotation_between,
    transpose,
)
from .state import (
    QUATERNION_TOLERANCE,
    SIGN_CONVENTIONS,
    AtmosphereReference,
    Attitude,
    Controls,
    FlightQuantities,
    FlightState,
    ForceMoment,
    InertiaTensor,
    MassProperties,
    ReferenceGeometry,
)
from .units import (
    Quantity,
    Vec3,
    dimension_of,
    from_si,
    require_dimension,
    si_unit_for_dimension,
    to_si,
)

__all__ = [
    "SCHEMA_VERSION",
    "REFERENCE_SECTION",
    "MOTION_SECTION",
    "MASS_SECTION",
    "OPERATING_SECTION",
    "FlyingVehicleState",
    "vehicle_state_from_payload",
    "canonical_vehicle_state",
    "vehicle_state_hash",
    "vehicle_state_provenance",
    "vehicle_state_change_sections",
    "airframe_invalidated_families",
    "vehicle_design_parameters",
    "canonical_json",
    "canonical_number",
    "content_digest",
    "normalize_numbers",
    "DerivedQuantity",
    "mach_number",
    "dynamic_pressure",
    "equivalent_airspeed",
    "weight_force",
    "Frame",
    "FRAME_KINDS",
    "FRAME_PARENT_KIND",
    "FRAME_CONVENTIONS",
    "IDENTITY",
    "frame_index",
    "frame_rotation",
    "rotation_between",
    "rotate_vector",
    "matmul",
    "matvec",
    "transpose",
    "Quantity",
    "Vec3",
    "dimension_of",
    "si_unit_for_dimension",
    "to_si",
    "from_si",
    "require_dimension",
    "MassProperties",
    "InertiaTensor",
    "Attitude",
    "AtmosphereReference",
    "FlightQuantities",
    "FlightState",
    "ReferenceGeometry",
    "Controls",
    "ForceMoment",
    "SIGN_CONVENTIONS",
    "QUATERNION_TOLERANCE",
]
