"""Generic aeroelasticity, flutter, forced response, gust and dynamic loads.

One contract serves turbomachinery blades, propellers/open rotors, wings, tails,
control surfaces, and flexible repeated structures. It provides linear/modal
coupling, a flutter/stability fidelity ladder, forced response (rotating-order,
gust, actuator, and pressure-spectrum), mistuning/cyclic assembly, atmospheric
gust/dynamic loads, and a contact/rub escalation seam. Every result carries
source/fidelity/units/validity/input-hash/software-identity/provenance, and
native FEA/CFD/FSI paths are capability-gated and fail closed.
"""

from .capabilities import (
    CapabilityState,
    NativeRequirement,
    native_capability,
    require_native,
)
from .contact import (
    ContactEventResult,
    RubContactSpec,
    evaluate_contact_event,
    solve_native_contact,
)
from .errors import (
    AeroelasticCapabilityUnavailable,
    AeroelasticError,
    AeroelasticLimitExceeded,
    AeroelasticValidityError,
)
from .flutter import (
    AerodynamicDampingEstimate,
    AeroelasticMode,
    AeroelasticSystem,
    EscalationDecision,
    FlutterBoundary,
    FlutterEscalationPolicy,
    StabilityCurve,
    StabilityPoint,
    TypicalSection,
    aerodynamic_damping_estimate,
    assess_flutter_escalation,
    build_stability_curve,
    evaluate_stability,
    solve_pk_flutter,
    solve_transient_fsi,
)
from .forced_response import (
    ForcedResponseResult,
    HarmonicForce,
    ModeResponse,
    actuator_force,
    evaluate_harmonic_response,
    pressure_spectrum_forces,
    rotating_order_force,
)
from .gust import (
    AtmosphericGust,
    GustKind,
    GustLoadResult,
    dryden_psd_m2_s,
    evaluate_continuous_gust,
    evaluate_discrete_gust,
)
from .mistuning import (
    CyclicMode,
    CyclicStructureSpec,
    MistuningResult,
    analyze_cyclic_structure,
    assemble_full_annulus,
    inverse_participation_ratio,
    localization_factor,
    sector_to_full_mapping,
)
from .modes import (
    GeneralizedForce,
    ModalBasis,
    ModalCouplingResult,
    PressureField,
    PressureSample,
    StructuralMode,
    assess_modal_resonance,
    map_pressure_to_modes,
    match_excitation_to_modes,
)
from .participants import (
    AEROELASTIC_PARTICIPANTS,
    AeroelasticParticipant,
    PortSpec,
    aeroelastic_participants,
    participant_ids,
    participant_native_states,
)
from .provenance import (
    DEFAULT_SOFTWARE,
    SOFTWARE_IDENTITY,
    SOFTWARE_VERSION,
    SoftwareIdentity,
    analytical_provenance,
    benchmark_provenance,
    native_provenance,
    reduced_provenance,
)
from .units import SI_UNITS, UnitError, require_unit
from .validity import AeroelasticFidelity, Validity, finite, finite_tuple

__all__ = [
    "AEROELASTIC_PARTICIPANTS",
    "DEFAULT_SOFTWARE",
    "SI_UNITS",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_VERSION",
    "AerodynamicDampingEstimate",
    "AeroelasticCapabilityUnavailable",
    "AeroelasticError",
    "AeroelasticFidelity",
    "AeroelasticLimitExceeded",
    "AeroelasticMode",
    "AeroelasticParticipant",
    "AeroelasticSystem",
    "AeroelasticValidityError",
    "AtmosphericGust",
    "CapabilityState",
    "ContactEventResult",
    "CyclicMode",
    "CyclicStructureSpec",
    "EscalationDecision",
    "FlutterBoundary",
    "FlutterEscalationPolicy",
    "ForcedResponseResult",
    "GeneralizedForce",
    "GustKind",
    "GustLoadResult",
    "HarmonicForce",
    "MistuningResult",
    "ModalBasis",
    "ModalCouplingResult",
    "ModeResponse",
    "NativeRequirement",
    "PortSpec",
    "PressureField",
    "PressureSample",
    "RubContactSpec",
    "SoftwareIdentity",
    "StabilityCurve",
    "StabilityPoint",
    "StructuralMode",
    "TypicalSection",
    "UnitError",
    "Validity",
    "actuator_force",
    "aerodynamic_damping_estimate",
    "aeroelastic_participants",
    "analytical_provenance",
    "analyze_cyclic_structure",
    "assemble_full_annulus",
    "assess_flutter_escalation",
    "assess_modal_resonance",
    "benchmark_provenance",
    "build_stability_curve",
    "dryden_psd_m2_s",
    "evaluate_contact_event",
    "evaluate_continuous_gust",
    "evaluate_discrete_gust",
    "evaluate_harmonic_response",
    "evaluate_stability",
    "finite",
    "finite_tuple",
    "inverse_participation_ratio",
    "localization_factor",
    "map_pressure_to_modes",
    "match_excitation_to_modes",
    "native_capability",
    "native_provenance",
    "participant_ids",
    "participant_native_states",
    "pressure_spectrum_forces",
    "reduced_provenance",
    "require_native",
    "require_unit",
    "rotating_order_force",
    "sector_to_full_mapping",
    "solve_native_contact",
    "solve_pk_flutter",
    "solve_transient_fsi",
]
