"""Multi-point off-design maps, controls, and operating-envelope optimization."""

from .aggregation import (
    AGGREGATION_MODES,
    AggregateOutcome,
    AggregationMode,
    PointObjective,
    aggregate_multipoint,
    aggregate_objective,
    aggregation_digest,
    objectives_from_matches,
    pareto_front,
)
from .envelope import (
    ENVELOPE_AXES,
    MAX_ENVELOPE_CELLS,
    MAX_REFINEMENT_SAMPLES,
    EnvelopeAxis,
    EnvelopeSpec,
    classify_match,
    envelope_result,
    generate_envelope,
    refine_envelope,
)
from .errors import (
    OffdesignCapabilityUnavailable,
    OffdesignError,
    OffdesignInputError,
)
from .matching import (
    MapReference,
    OperabilityLimits,
    PointMatch,
    corrected_conditions,
    corrected_speed,
    evaluate_multipoint,
    evaluate_point,
    match_digest,
    surge_margin_for,
)
from .native import (
    NATIVE_OFFDESIGN_CAPABILITY,
    NativeOffdesignRequest,
    native_offdesign_status,
    request_native_offdesign,
)
from .operating_point import (
    MAX_OFFDESIGN_POINTS,
    OperatingPoint,
    operating_points_hash,
)
from .results import (
    DEFAULT_OFFDESIGN_SOFTWARE,
    SOFTWARE_IDENTITY,
    SOFTWARE_VERSION,
    EnvelopeCell,
    MultiPointResult,
    OffdesignFidelity,
    OffdesignPointResult,
    OffdesignSoftware,
    OffdesignValidity,
    OperatingEnvelope,
    offdesign_provenance,
    point_result,
)
from .schedules import (
    SCHEDULE_VARIABLES,
    ControlChannel,
    ControlSchedule,
)

__all__ = [
    "AGGREGATION_MODES",
    "DEFAULT_OFFDESIGN_SOFTWARE",
    "ENVELOPE_AXES",
    "MAX_ENVELOPE_CELLS",
    "MAX_OFFDESIGN_POINTS",
    "MAX_REFINEMENT_SAMPLES",
    "NATIVE_OFFDESIGN_CAPABILITY",
    "SCHEDULE_VARIABLES",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_VERSION",
    "AggregateOutcome",
    "AggregationMode",
    "ControlChannel",
    "ControlSchedule",
    "EnvelopeAxis",
    "EnvelopeCell",
    "EnvelopeSpec",
    "MapReference",
    "MultiPointResult",
    "NativeOffdesignRequest",
    "OffdesignCapabilityUnavailable",
    "OffdesignError",
    "OffdesignFidelity",
    "OffdesignInputError",
    "OffdesignPointResult",
    "OffdesignSoftware",
    "OffdesignValidity",
    "OperabilityLimits",
    "OperatingEnvelope",
    "OperatingPoint",
    "PointMatch",
    "PointObjective",
    "aggregate_multipoint",
    "aggregate_objective",
    "aggregation_digest",
    "classify_match",
    "corrected_conditions",
    "corrected_speed",
    "envelope_result",
    "evaluate_multipoint",
    "evaluate_point",
    "generate_envelope",
    "match_digest",
    "native_offdesign_status",
    "objectives_from_matches",
    "offdesign_provenance",
    "operating_points_hash",
    "pareto_front",
    "point_result",
    "refine_envelope",
    "request_native_offdesign",
    "surge_margin_for",
]
