"""Requirements compiler and physics-based initial vehicle synthesis (AIRFRAME 06).

The compiler normalizes typed mission/performance/constraint requirements into a
unit-safe SI set with provenance and explicit conflict detection. Synthesis then
derives fixed-wing seeds from declared analytical/empirical relations, exposes
rotorcraft and lifting-body architecture seams, and projects seeds onto the
existing design-space and design-state contracts. All results are deterministic,
hashable, screening evidence only, and fail closed.
"""

from ..constraints import (
    DOWNSTREAM_CONSTRAINT_ADAPTERS,
    ConstraintEvaluation,
    ConstraintFinding,
    ConstraintObservation,
    evaluate_downstream_requirements,
)
from .errors import (
    RequirementCompileError,
    RequirementConflict,
    RequirementConflictError,
    RequirementError,
    SynthesisError,
    SynthesisInfeasibleError,
)
from .fixed_wing import (
    FixedWingAssumptions,
    generate_fixed_wing_seeds,
    requirement_bounds,
)
from .lifting_body import (
    LiftingBodyCampaignFixture,
    build_lifting_body_campaign_fixture,
)
from .methods import (
    METHODS,
    SYNTHESIS_MODEL,
    SYNTHESIS_MODEL_VERSION,
    MethodValidity,
    SynthesisQuantity,
    ValidityCheck,
)
from .report import SynthesisReport, synthesize_initial_seeds
from .requirements import (
    KINDS,
    METRIC_CATEGORIES,
    METRIC_DIMENSIONS,
    METRIC_ENFORCEMENT_ROUTES,
    OPERATORS,
    REQUIREMENTS_MODEL,
    REQUIREMENTS_MODEL_VERSION,
    CompiledRequirements,
    NormalizedRequirement,
    RequirementEnforcementRoute,
    RequirementSpec,
    compile_requirements,
    compile_requirements_payload,
    detect_conflicts,
    requirement_spec_from_payload,
)
from .rotor_airframe import (
    RotorAirframeCouplingResult,
    RotorAirframeNativeUnavailable,
    RotorAirframeSurface,
    RotorSurfaceLoad,
    VehicleTrimEffects,
    couple_rotor_airframe,
)
from .rotorcraft import (
    FlappingState,
    RotorcraftAssemblyResult,
    RotorcraftControls,
    RotorcraftFlightCondition,
    RotorcraftLimits,
    RotorcraftLoads,
    RotorcraftNativeUnavailable,
    RotorcraftResult,
    RotorcraftRotor,
    RotorcraftTrimResult,
    RotorWakeField,
    WakeExchange,
    evaluate_rotorcraft,
    evaluate_rotorcraft_assembly,
    rotor_wake_field,
    trim_rotorcraft,
)
from .seams import (
    RotorcraftCapabilityUnavailable,
    RotorcraftEnvelope,
    SeamResult,
    evaluate_rotorcraft_envelope,
    probe_rotorcraft_foundation,
    synthesize_lifting_body_seam,
    synthesize_rotorcraft_seam,
)
from .seeds import VehicleSeed, build_seed_design_space

__all__ = [
    "KINDS",
    "METHODS",
    "METRIC_CATEGORIES",
    "METRIC_DIMENSIONS",
    "METRIC_ENFORCEMENT_ROUTES",
    "OPERATORS",
    "REQUIREMENTS_MODEL",
    "REQUIREMENTS_MODEL_VERSION",
    "SYNTHESIS_MODEL",
    "SYNTHESIS_MODEL_VERSION",
    "CompiledRequirements",
    "ConstraintEvaluation",
    "ConstraintFinding",
    "ConstraintObservation",
    "DOWNSTREAM_CONSTRAINT_ADAPTERS",
    "FixedWingAssumptions",
    "LiftingBodyCampaignFixture",
    "MethodValidity",
    "NormalizedRequirement",
    "RequirementEnforcementRoute",
    "RequirementCompileError",
    "RequirementConflict",
    "RequirementConflictError",
    "RequirementError",
    "RequirementSpec",
    "SeamResult",
    "RotorcraftCapabilityUnavailable",
    "FlappingState",
    "RotorcraftAssemblyResult",
    "RotorcraftControls",
    "RotorcraftFlightCondition",
    "RotorcraftLimits",
    "RotorcraftLoads",
    "RotorcraftNativeUnavailable",
    "RotorcraftResult",
    "RotorcraftRotor",
    "RotorcraftTrimResult",
    "RotorWakeField",
    "WakeExchange",
    "evaluate_rotorcraft",
    "evaluate_rotorcraft_assembly",
    "trim_rotorcraft",
    "rotor_wake_field",
    "RotorAirframeCouplingResult",
    "RotorAirframeNativeUnavailable",
    "RotorAirframeSurface",
    "RotorSurfaceLoad",
    "VehicleTrimEffects",
    "couple_rotor_airframe",
    "RotorcraftEnvelope",
    "evaluate_rotorcraft_envelope",
    "probe_rotorcraft_foundation",
    "SynthesisError",
    "SynthesisInfeasibleError",
    "SynthesisQuantity",
    "SynthesisReport",
    "ValidityCheck",
    "VehicleSeed",
    "build_seed_design_space",
    "compile_requirements",
    "compile_requirements_payload",
    "detect_conflicts",
    "evaluate_downstream_requirements",
    "generate_fixed_wing_seeds",
    "build_lifting_body_campaign_fixture",
    "requirement_bounds",
    "requirement_spec_from_payload",
    "synthesize_initial_seeds",
    "synthesize_lifting_body_seam",
    "synthesize_rotorcraft_seam",
]
