"""Generic GD&T, tolerance stack-up, assembly, balance, and yield analysis.

This package turns typed, revisioned tolerance contracts into deterministic,
provenance-backed engineering results: worst-case/RSS/Monte-Carlo stack-up,
clearance and interference fits, insertion/access and fastener assembly checks,
rotating-body balance with manufacturing mass scatter, and production yield vs
declared hard limits. Every result carries source/fidelity/units/validity/
input-hash/software-identity/provenance. Native interference checking is
capability-gated and fails closed; no result is fabricated.

Public API (other workstreams import these exact paths):

    from aeroworkbench_tolerancing import (
        ToleranceClass, DistributionKind, DatumReference,
        ToleranceCallout, ToleranceContract, ResultEnvelope, SoftwareIdentity,
        StackupModel, StackupTerm, StackupResult,
        stackup_worst_case, stackup_statistical, stackup_monte_carlo, normal_cdf,
        MassElement, MassProperties, MassScatterElement, CorrectionPlane,
        BalanceSpec, ImbalanceState, BalanceAssessment, BalanceScatterResult,
        compute_mass_properties, assess_imbalance, assess_balance, balance_scatter,
        residual_unbalance_forcing,
        FitType, FitSpec, FitAssessment, InsertionPath, PathCheck, EdgeDistanceRule,
        FastenerJoint, JointCheck, AssemblyViolation, AssemblyReport,
        assess_fit, check_assembly, check_datums,
        YieldEstimate, RobustnessReport, estimate_yield, wilson_interval,
        assess_robustness, require_robust,
        limits_for, evaluate_limits, LimitEvaluation, LimitViolation,
        CapabilityState, NativeInspectionBackend, NativeInterferenceResult,
        native_interference_capability, require_native_interference,
        native_interference_check,
        TolerancingError, ToleranceContractError, StackupError, BalanceError,
        AssemblyError, YieldError, CapabilityUnavailable,
    )
"""

from .assembly import (
    AssemblyReport,
    AssemblyViolation,
    EdgeDistanceRule,
    FastenerJoint,
    FitAssessment,
    FitSpec,
    FitType,
    InsertionPath,
    JointCheck,
    PathCheck,
    assess_fit,
    check_assembly,
    check_datums,
)
from .balance import (
    BalanceAssessment,
    BalanceScatterResult,
    BalanceSpec,
    CorrectionPlane,
    ImbalanceState,
    MassElement,
    MassProperties,
    MassScatterElement,
    assess_balance,
    assess_imbalance,
    balance_scatter,
    compute_mass_properties,
    residual_unbalance_forcing,
)
from .capabilities import (
    CapabilityState,
    NativeInspectionBackend,
    NativeInterferenceResult,
    native_interference_capability,
    native_interference_check,
    require_native_interference,
)
from .contracts import (
    SOFTWARE_IDENTITY,
    SOFTWARE_VERSION,
    TOLERANCE_SCHEMA_VERSION,
    DatumReference,
    DistributionKind,
    ResultEnvelope,
    SoftwareIdentity,
    ToleranceCallout,
    ToleranceClass,
    ToleranceContract,
    build_envelope,
    deviation_scale,
    scale_of,
)
from .errors import (
    AssemblyError,
    BalanceError,
    CapabilityUnavailable,
    StackupError,
    ToleranceContractError,
    TolerancingError,
    YieldError,
)
from .limits import LimitEvaluation, LimitViolation, evaluate_limits, limits_for
from .robustness import (
    RobustnessReport,
    YieldEstimate,
    assess_robustness,
    estimate_yield,
    require_robust,
    robustness_from_mapping,
    wilson_interval,
)
from .stackup import (
    MAX_MONTE_CARLO_SAMPLES,
    StackupModel,
    StackupResult,
    StackupTerm,
    normal_cdf,
    stackup_monte_carlo,
    stackup_statistical,
    stackup_worst_case,
)

__all__ = [
    "MAX_MONTE_CARLO_SAMPLES",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_VERSION",
    "TOLERANCE_SCHEMA_VERSION",
    "AssemblyError",
    "AssemblyReport",
    "AssemblyViolation",
    "BalanceAssessment",
    "BalanceError",
    "BalanceScatterResult",
    "BalanceSpec",
    "CapabilityState",
    "CapabilityUnavailable",
    "CorrectionPlane",
    "DatumReference",
    "DistributionKind",
    "EdgeDistanceRule",
    "FastenerJoint",
    "FitAssessment",
    "FitSpec",
    "FitType",
    "ImbalanceState",
    "InsertionPath",
    "JointCheck",
    "LimitEvaluation",
    "LimitViolation",
    "MassElement",
    "MassProperties",
    "MassScatterElement",
    "NativeInspectionBackend",
    "NativeInterferenceResult",
    "PathCheck",
    "ResultEnvelope",
    "RobustnessReport",
    "SoftwareIdentity",
    "StackupError",
    "StackupModel",
    "StackupResult",
    "StackupTerm",
    "ToleranceCallout",
    "ToleranceClass",
    "ToleranceContract",
    "ToleranceContractError",
    "TolerancingError",
    "YieldError",
    "YieldEstimate",
    "assess_balance",
    "assess_fit",
    "assess_imbalance",
    "assess_robustness",
    "balance_scatter",
    "build_envelope",
    "check_assembly",
    "check_datums",
    "compute_mass_properties",
    "deviation_scale",
    "estimate_yield",
    "evaluate_limits",
    "limits_for",
    "native_interference_capability",
    "native_interference_check",
    "normal_cdf",
    "require_native_interference",
    "require_robust",
    "residual_unbalance_forcing",
    "robustness_from_mapping",
    "scale_of",
    "stackup_monte_carlo",
    "stackup_statistical",
    "stackup_worst_case",
    "wilson_interval",
]
