"""High-lift, nonlinear stall and post-stall aerodynamic fidelity (VS 04).

Public API import path::

    from aeroworkbench_vehicle_systems.highlift import (
        HighLiftConfiguration, HighLiftDevice, DeflectionSchedule,
        SectionStallParameters, WingPlanform,
        evaluate_section, evaluate_finite_wing,
        check_stall_constraint, evaluate_stall_margin, assess_deep_stall,
        check_control_authority, solve_highlift_aero, plan_highlift_fidelity,
        solve_dynamic_stall, promote_to_rans, ...
    )

Every result carries source/fidelity/units/validity/input-hash/software-identity
and provenance; native backends are capability-gated and fail closed.
"""

from __future__ import annotations

from .authority import (
    MODEL_AUTHORITY,
    AuthoritySurface,
    ControlAuthorityVerdict,
    check_control_authority,
)
from .contracts import (
    DEFAULT_SOFTWARE,
    HL_UNITS,
    SOFTWARE_IDENTITY,
    SOFTWARE_VERSION,
    HighLiftFidelity,
    ResultMeta,
    SoftwareIdentity,
    Validity,
    result_meta,
)
from .devices import (
    DEVICE_KINDS,
    MODEL_DEVICES,
    ConfigurationDelta,
    DeflectionSchedule,
    DeviceIncrements,
    HighLiftConfiguration,
    HighLiftDevice,
    ScheduleEntry,
)
from .errors import (
    CapabilityUnavailable,
    HighLiftError,
    LimitExceeded,
    ValidityError,
    finite,
    finite_vector,
)
from .fixtures import (
    MODEL_FIXTURES,
    canonical_flap,
    canonical_slat,
    clean_configuration,
    deflection_schedule,
    landing_configuration,
    simple_airfoil_section,
    small_wing_planform,
    takeoff_configuration,
)
from .ladder import (
    HIGHLIFT_LADDER,
    STALL_ESCALATION_MARGIN_DEG,
    HighLiftAeroResult,
    escalation_for_margin,
    plan_highlift_fidelity,
    solve_highlift_aero,
    validity_signals_for_ladder,
)
from .native import (
    MESH_PROMOTION_REQUIREMENT,
    MODEL_PROMOTION,
    NATIVE_HIGHLIFT_RANS_REQUIREMENT,
    NativeHighLiftStatus,
    RansPromotionTicket,
    native_highlift_provenance,
    native_highlift_status,
    native_validity,
    promote_to_rans,
    require_native_highlift,
)
from .section import (
    MODEL_SECTION,
    REGIMES,
    SectionNonlinearResult,
    SectionStallParameters,
    classify_regime,
    evaluate_section,
    section_polar_table,
)
from .stall import (
    MODEL_DEEPSTALL,
    MODEL_MARGIN,
    WARNING_LEVELS,
    DeepStallAssessment,
    StallMargin,
    assess_deep_stall,
    evaluate_stall_margin,
    warning_level,
)
from .unsteady import (
    MODEL_UNSTEADY,
    NATIVE_UNSTEADY_REQUIREMENT,
    DynamicStallBackend,
    DynamicStallRequest,
    DynamicStallResult,
    DynamicStallSolution,
    quasi_steady_valid,
    require_dynamic_stall_capability,
    solve_dynamic_stall,
)
from .wing import (
    MODEL_WING,
    FiniteWingResult,
    StallConstraintVerdict,
    WingPlanform,
    check_stall_constraint,
    evaluate_finite_wing,
    linear_vlm_lift,
    require_nonlinear_guard,
)

__all__ = [
    "DEVICE_KINDS",
    "HIGHLIFT_LADDER",
    "HL_UNITS",
    "MESH_PROMOTION_REQUIREMENT",
    "MODEL_AUTHORITY",
    "MODEL_DEEPSTALL",
    "MODEL_DEVICES",
    "MODEL_FIXTURES",
    "MODEL_MARGIN",
    "MODEL_PROMOTION",
    "MODEL_SECTION",
    "MODEL_UNSTEADY",
    "MODEL_WING",
    "NATIVE_HIGHLIFT_RANS_REQUIREMENT",
    "NATIVE_UNSTEADY_REQUIREMENT",
    "REGIMES",
    "STALL_ESCALATION_MARGIN_DEG",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_VERSION",
    "WARNING_LEVELS",
    "AuthoritySurface",
    "CapabilityUnavailable",
    "ConfigurationDelta",
    "ControlAuthorityVerdict",
    "DeepStallAssessment",
    "DeflectionSchedule",
    "DeviceIncrements",
    "DynamicStallBackend",
    "DynamicStallRequest",
    "DynamicStallResult",
    "DynamicStallSolution",
    "FiniteWingResult",
    "HighLiftAeroResult",
    "HighLiftConfiguration",
    "HighLiftDevice",
    "HighLiftError",
    "HighLiftFidelity",
    "LimitExceeded",
    "NativeHighLiftStatus",
    "RansPromotionTicket",
    "ResultMeta",
    "ScheduleEntry",
    "SectionNonlinearResult",
    "SectionStallParameters",
    "SoftwareIdentity",
    "StallConstraintVerdict",
    "StallMargin",
    "Validity",
    "ValidityError",
    "WingPlanform",
    "assess_deep_stall",
    "canonical_flap",
    "canonical_slat",
    "check_control_authority",
    "check_stall_constraint",
    "classify_regime",
    "clean_configuration",
    "DEFAULT_SOFTWARE",
    "deflection_schedule",
    "escalation_for_margin",
    "evaluate_finite_wing",
    "evaluate_section",
    "evaluate_stall_margin",
    "finite",
    "finite_vector",
    "landing_configuration",
    "linear_vlm_lift",
    "native_highlift_provenance",
    "native_highlift_status",
    "native_validity",
    "plan_highlift_fidelity",
    "promote_to_rans",
    "quasi_steady_valid",
    "require_dynamic_stall_capability",
    "require_native_highlift",
    "require_nonlinear_guard",
    "result_meta",
    "section_polar_table",
    "simple_airfoil_section",
    "small_wing_planform",
    "solve_dynamic_stall",
    "solve_highlift_aero",
    "takeoff_configuration",
    "validity_signals_for_ladder",
    "warning_level",
]
