"""Transonic/supersonic external-aero design with shock/wave-drag fidelity (VS 08).

Screening seams (compressibility corrections, Korn drag rise, Sears-Haack and
area-rule wave drag, Ackeret supersonic sections, Korn-derived design guidance)
share one typed envelope carrying source/fidelity/units/validity/input-hash/
software-identity/provenance. Shock location and shock-sensitive wave drag are
owned by the capability-gated native OpenFOAM/SU2 seam, which fails closed when
no backend is wired. Hypersonic/high-enthalpy flow is explicitly out of scope.

Public API (other workstreams import these exact paths)::

    from aeroworkbench_vehicle_systems.transonic import (
        FlowRegime, TransonicFidelity, Validity, ResultEnvelope,
        ShockFeature, ShockFeatureResult,
        classify_regime, apply_correction, assess_drag_rise,
        sears_haack_wave_drag, assess_area_rule, assess_supersonic_section,
        normal_shock_ratios, required_sweep_deg, escalation_for_mach,
        promotion_for, solve_native_compressible,
    )
"""

from .contracts import (
    SOFTWARE_IDENTITY,
    SOFTWARE_VERSION,
    TRANSONIC_SCHEMA_VERSION,
    TRANSONIC_UNITS,
    FlowRegime,
    ResultEnvelope,
    ShockFeature,
    ShockFeatureResult,
    SoftwareIdentity,
    TransonicFidelity,
    Validity,
    analytical_envelope,
    analytical_shock_feature,
    content_digest,
    native_envelope,
)
from .corrections import (
    KARMAN_TSIEN_MAX_MACH,
    LAITONE_MAX_MACH,
    PRANDTL_GLAUERT_MAX_MACH,
    CorrectionResult,
    apply_correction,
    compressible_derivative,
    karman_tsien,
    laitone,
    prandtl_glauert,
)
from .design import (
    ConstraintEvaluation,
    TipGuidance,
    buffet_boundary_cl,
    compatible_derivative,
    evaluate_transonic_constraints,
    max_thickness_ratio,
    required_sweep_deg,
    tip_section_guidance,
    transonic_design_constraints,
)
from .drag_rise import (
    CRITICAL_TO_DIVERGENCE_OFFSET,
    DRAG_RISE_EXPONENT,
    DRAG_RISE_FACTOR,
    DragRiseResult,
    assess_drag_rise,
    critical_mach,
    drag_divergence_mach,
    korn_drag_divergence,
    wave_drag_rise,
)
from .errors import (
    TransonicCapabilityUnavailable,
    TransonicContractError,
    TransonicError,
    TransonicOutOfScope,
    TransonicValidityError,
)
from .native import (
    COMPRESSIBLE_EXECUTABLES,
    CompressibleCapability,
    NativeCompressibleBackend,
    NativeCompressibleReceipt,
    NativeCompressibleRequest,
    NativeCompressibleSolution,
    native_compressible_capability,
    prepare_compressible_case,
    probe_any_compressible_capability,
    probe_compressible_capability,
    require_native_compressible,
    solve_native_compressible,
)
from .policy import (
    COMPRESSIBLE_LADDER,
    THERMAL_COUPLING_MIN_MACH,
    Escalation,
    PromotionRequirement,
    escalation_for_mach,
    heating_seam_required,
    plan_compressible_fidelity,
    promotion_for,
)
from .regime import (
    HYPERSONIC_MIN_MACH,
    INCOMPRESSIBLE_MAX_MACH,
    SUBSONIC_MAX_MACH,
    SUPERSONIC_MAX_MACH,
    TRANSONIC_MAX_MACH,
    assert_not_hypersonic,
    classify_regime,
    is_shock_regime,
    regime_of,
)
from .supersonic import (
    MAX_ALPHA_DEG,
    MAX_THICKNESS_RATIO,
    SupersonicAssessment,
    ackeret_lift,
    assess_supersonic_section,
    double_wedge_wave_drag,
    normal_shock_ratios,
)
from .wave_drag import (
    AREA_PENALTY_FACTOR,
    AREA_SMOOTHNESS_LIMIT,
    AreaRuleResult,
    SearsHaackResult,
    area_rule_assessment,
    assess_area_rule,
    require_supersonic_band,
    sears_haack_wave_drag,
)

__all__ = [
    "AREA_PENALTY_FACTOR",
    "AREA_SMOOTHNESS_LIMIT",
    "COMPRESSIBLE_EXECUTABLES",
    "COMPRESSIBLE_LADDER",
    "CRITICAL_TO_DIVERGENCE_OFFSET",
    "DRAG_RISE_EXPONENT",
    "DRAG_RISE_FACTOR",
    "HYPERSONIC_MIN_MACH",
    "INCOMPRESSIBLE_MAX_MACH",
    "KARMAN_TSIEN_MAX_MACH",
    "LAITONE_MAX_MACH",
    "MAX_ALPHA_DEG",
    "MAX_THICKNESS_RATIO",
    "PRANDTL_GLAUERT_MAX_MACH",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_VERSION",
    "SUBSONIC_MAX_MACH",
    "SUPERSONIC_MAX_MACH",
    "THERMAL_COUPLING_MIN_MACH",
    "TRANSONIC_MAX_MACH",
    "TRANSONIC_SCHEMA_VERSION",
    "TRANSONIC_UNITS",
    "AreaRuleResult",
    "CompressibleCapability",
    "ConstraintEvaluation",
    "CorrectionResult",
    "DragRiseResult",
    "Escalation",
    "FlowRegime",
    "NativeCompressibleBackend",
    "NativeCompressibleReceipt",
    "NativeCompressibleRequest",
    "NativeCompressibleSolution",
    "PromotionRequirement",
    "ResultEnvelope",
    "ShockFeature",
    "ShockFeatureResult",
    "SearsHaackResult",
    "SoftwareIdentity",
    "SupersonicAssessment",
    "TipGuidance",
    "TransonicCapabilityUnavailable",
    "TransonicContractError",
    "TransonicError",
    "TransonicFidelity",
    "TransonicOutOfScope",
    "TransonicValidityError",
    "Validity",
    "ackeret_lift",
    "analytical_envelope",
    "analytical_shock_feature",
    "apply_correction",
    "area_rule_assessment",
    "assess_area_rule",
    "assess_drag_rise",
    "assess_supersonic_section",
    "assert_not_hypersonic",
    "buffet_boundary_cl",
    "classify_regime",
    "compatible_derivative",
    "compressible_derivative",
    "content_digest",
    "critical_mach",
    "double_wedge_wave_drag",
    "drag_divergence_mach",
    "escalation_for_mach",
    "evaluate_transonic_constraints",
    "heating_seam_required",
    "is_shock_regime",
    "karman_tsien",
    "korn_drag_divergence",
    "laitone",
    "max_thickness_ratio",
    "native_compressible_capability",
    "native_envelope",
    "normal_shock_ratios",
    "plan_compressible_fidelity",
    "prandtl_glauert",
    "prepare_compressible_case",
    "probe_any_compressible_capability",
    "probe_compressible_capability",
    "promotion_for",
    "regime_of",
    "require_native_compressible",
    "require_supersonic_band",
    "required_sweep_deg",
    "sears_haack_wave_drag",
    "solve_native_compressible",
    "tip_section_guidance",
    "transonic_design_constraints",
    "wave_drag_rise",
]
