"""Generic unshrouded/open/single/coaxial propulsor workflows.

The package represents one or more rotating propulsor rows without ever
requiring a duct or stator: architecture and placement, real propeller/open-
rotor geometry, low-cost actuator-disk and blade-element momentum screening,
a capability-gated native reduced-wake/CFD seam, generic airframe installation
coupling, controls/constraints, and verification fixtures. Every result carries
source/fidelity/units/validity/input-hash/software-identity/provenance; native
capabilities and declared limits fail closed.
"""

from .aero import (
    MAX_TIP_MACH,
    ActuatorDiskResult,
    BladeStation,
    CoaxialCoupling,
    CoaxialResult,
    Inflow,
    RotorAeroResult,
    RotorSpec,
    StationLoad,
    coaxial_coupling,
    evaluate_actuator_disk,
    evaluate_coaxial_pair,
    evaluate_rotor,
    rotor_spec_from_geometry,
)
from .architecture import (
    DIRECTIONS,
    PITCH_CONTROLS,
    PLACEMENTS,
    SCHEMA_VERSION,
    SHAFT_KINDS,
    CyclicPitchSeam,
    InstallationFrame,
    PitchSchedule,
    PropulsorArchitecture,
    RotorDeclaration,
    ShaftDeclaration,
    SpinnerGeometry,
    architecture_from_payload,
    architecture_hash,
    architecture_provenance,
    canonical_architecture,
)
from .controls import (
    ConstraintReport,
    DesignVariable,
    PropulsorConstraints,
    PropulsorDesignSpace,
    apply_collective_schedule,
    blade_passing_frequency_hz,
    check_constraints,
    resonance_margin,
    rotor_design_space,
    validate_operating_envelope,
)
from .geometry import (
    PropellerGeometry,
    SpanSection,
    coaxial_spacing_ok,
    geometry_hash,
)
from .installation import (
    Installation,
    InstalledInflow,
    SlipstreamField,
    VehicleLoads,
    effective_inflow,
    installed_loads,
    slipstream_field,
)
from .native import (
    NATIVE_LEVELS,
    CapabilityState,
    NativeAeroResult,
    NativeRequest,
    WakeBackend,
    native_capability,
    promote_to_native,
    require_native,
)
from .participants import (
    PROPULSOR_PARTICIPANTS,
    ComponentParticipant,
    PortSpec,
    declared_levels,
    native_requirements,
    participant_ids,
    propulsor_participants,
)
from .provenance import (
    SOFTWARE_IDENTITY,
    SOFTWARE_VERSION,
    analytical_provenance,
    native_provenance,
    reduced_provenance,
)
from .validity import (
    AeroFidelity,
    CapabilityUnavailable,
    LimitExceeded,
    PropulsorError,
    Validity,
    finite,
    finite_vector,
    flag,
    integer,
    nonempty,
)

__all__ = [
    "DIRECTIONS",
    "MAX_TIP_MACH",
    "NATIVE_LEVELS",
    "PITCH_CONTROLS",
    "PLACEMENTS",
    "PROPULSOR_PARTICIPANTS",
    "SCHEMA_VERSION",
    "SHAFT_KINDS",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_VERSION",
    "ActuatorDiskResult",
    "AeroFidelity",
    "BladeStation",
    "CapabilityState",
    "CapabilityUnavailable",
    "CoaxialCoupling",
    "CoaxialResult",
    "ComponentParticipant",
    "ConstraintReport",
    "CyclicPitchSeam",
    "DesignVariable",
    "Inflow",
    "Installation",
    "InstallationFrame",
    "InstalledInflow",
    "LimitExceeded",
    "NativeAeroResult",
    "NativeRequest",
    "PitchSchedule",
    "PortSpec",
    "PropellerGeometry",
    "PropulsorArchitecture",
    "PropulsorConstraints",
    "PropulsorDesignSpace",
    "PropulsorError",
    "RotorAeroResult",
    "RotorDeclaration",
    "RotorSpec",
    "ShaftDeclaration",
    "SlipstreamField",
    "SpanSection",
    "SpinnerGeometry",
    "StationLoad",
    "Validity",
    "VehicleLoads",
    "WakeBackend",
    "analytical_provenance",
    "apply_collective_schedule",
    "architecture_from_payload",
    "architecture_hash",
    "architecture_provenance",
    "blade_passing_frequency_hz",
    "canonical_architecture",
    "check_constraints",
    "coaxial_coupling",
    "coaxial_spacing_ok",
    "declared_levels",
    "effective_inflow",
    "evaluate_actuator_disk",
    "evaluate_coaxial_pair",
    "evaluate_rotor",
    "finite",
    "finite_vector",
    "flag",
    "geometry_hash",
    "installed_loads",
    "integer",
    "native_capability",
    "native_provenance",
    "native_requirements",
    "nonempty",
    "participant_ids",
    "promote_to_native",
    "propulsor_participants",
    "reduced_provenance",
    "require_native",
    "resonance_margin",
    "rotor_design_space",
    "rotor_spec_from_geometry",
    "slipstream_field",
    "validate_operating_envelope",
]
