"""Landing gear, ground operations, and takeoff/landing dynamics (VS 06).

Public API import path::

    from aeroworkbench_vehicle_systems.landing_gear import (
        LandingGearAssembly, tricycle_gear, skid_gear,
        RunwaySpec, RunwaySurface,
        GroundVehicleModel, DragPolar, ThrustModel,
        simulate_takeoff, simulate_landing, simulate_rejected_takeoff,
        evaluate_shock_stroke, check_ground_stability, check_clearance,
        export_load_cases, ...
    )

Every result carries source/fidelity/units/validity/input-hash/software-identity
and provenance; native backends are capability-gated and fail closed.
"""

from __future__ import annotations

from .clearance import (
    ClearancePoint,
    ClearanceResult,
    PointClearance,
    check_clearance,
    require_clearance,
    rotation_clearance_points,
)
from .contracts import (
    DEFAULT_SOFTWARE,
    LG_UNITS,
    SOFTWARE_IDENTITY,
    SOFTWARE_VERSION,
    LandingGearFidelity,
    ResultMeta,
    SoftwareIdentity,
    Validity,
    result_meta,
)
from .errors import (
    CapabilityUnavailable,
    GroundStabilityError,
    LandingGearError,
    LimitExceeded,
    UnitError,
    finite,
    finite_vector,
)
from .friction import (
    FrictionResult,
    RunwaySpec,
    RunwaySurface,
    braking_force,
    friction_result_meta,
    rolling_resistance_force,
    side_friction_force,
    steer_angle_for_radius_rad,
    steering_turn_rate_rad_s,
)
from .geometry import (
    BODY_AXES,
    BrakeSpec,
    GearArchitecture,
    GearLegSpec,
    GearRole,
    LandingGearAssembly,
    ShockAbsorberSpec,
    WheelSpec,
    skid_gear,
    tricycle_gear,
)
from .ground_effect import (
    GroundEffectResult,
    NativeGroundEffectStatus,
    apply_ground_effect,
    ground_effect_factor,
    native_ground_effect_status,
    require_native_ground_effect,
)
from .loads import (
    GearLoadCase,
    LoadCaseExport,
    LoadCaseKind,
    braking_load_case,
    export_load_cases,
    native_structural_capability,
    require_native_structural,
    touchdown_load_case,
    turning_load_case,
)
from .native import (
    NATIVE_GEAR_STRUCTURE_REQUIREMENT,
    NATIVE_GROUND_DYNAMICS_REQUIREMENT,
    NativeGroundDynamicsStatus,
    native_ground_dynamics_provenance,
    native_ground_dynamics_status,
    require_native_gear_structure,
    require_native_ground_dynamics,
)
from .performance import (
    DragPolar,
    GroundVehicleModel,
    LandingResult,
    RejectedTakeoffResult,
    TakeoffResult,
    ThrustModel,
    isa_density_kg_m3,
    simulate_landing,
    simulate_rejected_takeoff,
    simulate_takeoff,
)
from .shock import ShockStrokeResult, evaluate_shock_stroke
from .stability import (
    GearReaction,
    GroundStabilityResult,
    check_ground_stability,
    require_stable_ground,
)

__all__ = [
    "BODY_AXES",
    "DEFAULT_SOFTWARE",
    "LG_UNITS",
    "NATIVE_GEAR_STRUCTURE_REQUIREMENT",
    "NATIVE_GROUND_DYNAMICS_REQUIREMENT",
    "SOFTWARE_IDENTITY",
    "SOFTWARE_VERSION",
    "BrakeSpec",
    "CapabilityUnavailable",
    "ClearancePoint",
    "ClearanceResult",
    "DragPolar",
    "FrictionResult",
    "GearArchitecture",
    "GearLegSpec",
    "GearLoadCase",
    "GearReaction",
    "GearRole",
    "GroundEffectResult",
    "GroundStabilityError",
    "GroundStabilityResult",
    "GroundVehicleModel",
    "LandingGearAssembly",
    "LandingGearError",
    "LandingGearFidelity",
    "LandingResult",
    "LimitExceeded",
    "LoadCaseExport",
    "LoadCaseKind",
    "NativeGroundDynamicsStatus",
    "NativeGroundEffectStatus",
    "PointClearance",
    "RejectedTakeoffResult",
    "ResultMeta",
    "RunwaySpec",
    "RunwaySurface",
    "ShockAbsorberSpec",
    "ShockStrokeResult",
    "SoftwareIdentity",
    "TakeoffResult",
    "ThrustModel",
    "UnitError",
    "Validity",
    "WheelSpec",
    "apply_ground_effect",
    "braking_force",
    "braking_load_case",
    "check_clearance",
    "check_ground_stability",
    "evaluate_shock_stroke",
    "export_load_cases",
    "finite",
    "finite_vector",
    "friction_result_meta",
    "ground_effect_factor",
    "isa_density_kg_m3",
    "native_ground_dynamics_provenance",
    "native_ground_dynamics_status",
    "native_ground_effect_status",
    "native_structural_capability",
    "require_clearance",
    "require_native_gear_structure",
    "require_native_ground_dynamics",
    "require_native_ground_effect",
    "require_native_structural",
    "require_stable_ground",
    "result_meta",
    "rolling_resistance_force",
    "rotation_clearance_points",
    "side_friction_force",
    "simulate_landing",
    "simulate_rejected_takeoff",
    "simulate_takeoff",
    "skid_gear",
    "steer_angle_for_radius_rad",
    "steering_turn_rate_rad_s",
    "touchdown_load_case",
    "tricycle_gear",
    "turning_load_case",
]
